### ISSUE TITLE
Build fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by MushyMiddle** [develar/osslsigncode#1]
Hi.  I tried to build on Ubuntu 18.04, and the build fails with the following.  Build was clean on 16.04 (no warnings or errors)...

gcc -DHAVE_CONFIG_H -I.    -I/usr/include/libgsf-1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libxml2  -I/usr/include/x86_64-linux-gnu -g -O2 -MT osslsigncode.o -MD -MP -MF .deps/osslsigncode.Tpo -c -o osslsigncode.o osslsigncode.c
osslsigncode.c: In function ‘createOpus’:
osslsigncode.c:453:36: warning: implicit declaration of function ‘M_ASN1_IA5STRING_new’; did you mean ‘ASN1_IA5STRING_new’? [-Wimplicit-function-declaration]
   info->programName->value.ascii = M_ASN1_IA5STRING_new();
                                    ^~~~~~~~~~~~~~~~~~~~
                                    ASN1_IA5STRING_new
osslsigncode.c:453:34: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   info->programName->value.ascii = M_ASN1_IA5STRING_new();
                                  ^
osslsigncode.c:461:29: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   info->moreInfo->value.url = M_ASN1_IA5STRING_new();
                             ^
osslsigncode.c: In function ‘add_timestamp’:
osslsigncode.c:612:14: error: storage size of ‘mdctx’ isn’t known
   EVP_MD_CTX mdctx;
              ^~~~~
osslsigncode.c:624:3: warning: implicit declaration of function ‘M_ASN1_OCTET_STRING_set’; did you mean ‘ASN1_OCTET_STRING_set’? [-Wimplicit-function-declaration]
   M_ASN1_OCTET_STRING_set(req->messageImprint->digest, mdbuf, EVP_MD_size(md));
   ^~~~~~~~~~~~~~~~~~~~~~~
   ASN1_OCTET_STRING_set
osslsigncode.c: In function ‘cleanup_lib_state’:
osslsigncode.c:819:2: warning: ‘ERR_remove_thread_state’ is deprecated [-Wdeprecated-declarations]
  ERR_remove_thread_state(NULL);
  ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/crypto.h:32:0,
                 from /usr/include/openssl/bio.h:20,
                 from /usr/include/openssl/err.h:21,
                 from osslsigncode.c:106:
/usr/include/openssl/err.h:247:1: note: declared here
 DEPRECATEDIN_1_1_0(void ERR_remove_thread_state(void *))
 ^
osslsigncode.c: At top level:
osslsigncode.c:927:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
 DECLARE_STACK_OF(ASN1_OCTET_STRING)
 ^~~~~~~~~~~~~~~~
osslsigncode.c: In function ‘DECLARE_STACK_OF’:
osslsigncode.c:936:1: error: expected declaration specifiers before ‘DECLARE_STACK_OF’
 DECLARE_STACK_OF(SpcAttributeTypeAndOptionalValue)
 ^~~~~~~~~~~~~~~~
osslsigncode.c:1002:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
...

**Comment by siennathesane** [comment]
Yeah, I'm hitting this issue, too. I think it has to do with the version of GCC you use.
